name: "Run bricktools check"
description: "Runs bricktools::check on the current brick"
runs:
  using: 'docker'
  image: 'docker://insilica/biobricks:latest'   
  args: ['${{ github.event.repository }}']
  entrypoint: 'bricktools-check.sh'