name: "Run bricktools check"
description: "Runs bricktools::check on the current brick"
runs:
  using: "composite"
  steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v1
      with:
        use-public-rspm: true
    - name: Install dvc
      run: |
        sudo wget https://dvc.org/deb/dvc.list -O /etc/apt/sources.list.d/dvc.list
        wget -qO - https://dvc.org/deb/iterative.asc | sudo apt-key add -
        sudo apt update
        sudo apt install dvc
      shell: bash
    - name: install devtools
      run: |
        install.packages("devtools")
      shell: Rscript {0}
    - name: install bricktools
      run: |
        devtools::install_github("biobricks-ai/bricktools")
      shell: Rscript {0}
    - name: bricktools check
      run: |
        bricktools::check(".")
      shell: Rscript {0}