name: "Run bricktools check"
description: "Runs bricktools::check on the current brick"
runs:
  using: "docker"
  image: insilica/biobricks:2.0
  steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: bricktools check
      run: bricktools::check(".")
      shell: Rscript {0}