name: Add latest tag to new release
on:
  release:
    types: [published]

jobs:
  run:
    name: Run local action
    runs-on: ubuntu-latest
    steps:
      - name: Latest tag
        uses: EndBug/latest-tag@v1.5.0
        env:
          GITHUB_TOKEN: ${{ github.token }}